### ISSUE TITLE
InvalidToken without changes on the secret key

### ISSUE THREAD

**Issue by Bufias** [orcasgit/django-fernet-fields#19]
Hello, I've got an issue with django-fernet-fields. I am using `Django 1.11` and `django-fernet-fields 0.5`. When I am trying to access a model that contains 2 attributes encrypted as `EncryptedTextField` , even from the admin site, Django is raising this error:
```
[2019/08/16 08:55:27] django.request ERROR [...] Internal Server Error: /admin/...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cryptography/fernet.py", line 104, in _verify_signature
    h.verify(data[-32:])
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/primitives/hmac.py", line 66, in verify
    ctx.verify(signature)
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.6/site-packages/cryptography/fernet.py", line 75, in decrypt
    return self._decrypt_data(data, timestamp, ttl)
  File "/usr/local/lib/python3.6/site-packages/cryptography/fernet.py", line 117, in _decrypt_data
    self._verify_signature(data)
  File "/usr/local/lib/python3.6/site-packages/cryptography/fernet.py", line 106, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken
```
I am not defining any key for encryption/decryption, so I assume (according to the docs) that the key used to encrypt/decrypt is my Django secret key. I am pretty sure this key has not changed (the only thing I changed was my database address, but it is exactly the same database).
If you can point me in a right direction to solve this issue would be great. Otherwise, there might be an issue with django-fernet-fields.
Thanks in advance.

**Comment by Bufias** [comment]
Ok, MY FAULT. Sorry if someone has been losing time with this. After hard investigation I realized that I had a problem during a deploy: a second key was used to encrypt a couple of rows. So I had little mess in one of the tables.
